server:
  port: 9100

spring:
  application:
    name: ao-platform-auth

  profiles:
    active: dev

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  mybatis-plus:
    configuration:
      map-underscore-to-camel-case: true

  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
        group: DEFAULT_GROUP
  config:
    import:
      - nacos:ao-platform-auth.yaml
      - nacos:ao-platform-auth-${spring.profiles.active}.yaml
