include:
  - standalone-mysql.yaml

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: zhurong-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - zhurong-network
  # zhurong-platform-gateway 服务
  zhurong-platform-gateway:
    image: crpi-8o01gg1zrswkepyk.cn-shenzhen.personal.cr.aliyuncs.com/nbaliyun/zhurong-platform-gateway:0.0.9
    container_name: zhurong-platform-gateway
    ports:
      - "9000:9000"
    depends_on:
      - nacos
    volumes:
      - ./logs/gateway:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
        #- SPRING_CLOUD_NACOS_DISCOVERY_IP=192.168.30.221
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
    restart: always
    networks:
      - zhurong-network

  # zhurong-platform-auth 服务
  zhurong-platform-auth:
    image: crpi-8o01gg1zrswkepyk.cn-shenzhen.personal.cr.aliyuncs.com/nbaliyun/zhurong-platform-auth:0.0.14
    container_name: zhurong-platform-auth
    ports:
      - "9100:9100"
    depends_on:
      - nacos
    volumes:
      - ./logs/auth:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
      #- SPRING_CLOUD_NACOS_DISCOVERY_IP=192.168.30.221
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
    restart: always
    networks:
      - zhurong-network

  # zhurong-platform-core 服务
  zhurong-platform-core:
    image: crpi-8o01gg1zrswkepyk.cn-shenzhen.personal.cr.aliyuncs.com/nbaliyun/zhurong-platform-core:0.0.30
    container_name: zhurong-platform-core
    ports:
      - "9200:9200"
    depends_on:
      - nacos
        #- rabbitmq
    volumes:
      - ./logs/core:/app/logs
      # 宿主windows机文件夹挂载
      # docker-desktop下使用windows路径映射
      # wsl系统内使用/mnt/d或者/mnt/c路径映射
      # 左侧是宿主机路径，右侧是core容器内固定路径。
      # 文件统一存储目录（文件存在宿主机上）
      - D:/Zhurong/shared-files:/app/data/shared-files
      # - /mnt/d/Zhurong/shared-files:/app/data/shared-files
      # 共享目录映射（外部系统可能会发共享文件夹图纸路径，如果是其他协议就不需要做这个映射，部署在docker容器内的core使用/app/source/shared-files查找文件）
      - windows-share:/app/source/shared-files
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER_ADDR=nacos:8848
        #- SPRING_CLOUD_NACOS_DISCOVERY_IP=192.168.30.221
      - SPRING_CLOUD_NACOS_CONFIG_SERVER_ADDR=nacos:8848
    restart: always
    networks:
      - zhurong-network
  # 前端      
  zhurong-nginx:
    image: crpi-8o01gg1zrswkepyk.cn-shenzhen.personal.cr.aliyuncs.com/nbaliyun/zhurong-platform-custom-xybaoyuan-nginx:0.0.2
    container_name: zhurong-platform-custom-xybaoyuan-nginx
    ports:
      - "9001:80"
    depends_on:
      - zhurong-platform-gateway
    restart: always
    networks:
      - zhurong-network

volumes:
  windows-share:
    name: windows-share
    driver: local
    driver_opts:
      type: cifs
      device: "//192.168.20.212/database$"
      o: "username=${SMB_USERNAME},password=${SMB_PASSWORD},file_mode=0777,dir_mode=0777"

networks:
  zhurong-network:
    driver: bridge
