version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: ao-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - ao-network

  nacos:
    image: nacos/nacos-server:v3.1.1
    container_name: ao-nacos
    restart: always
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_SQL_INIT_PLATFORM=postgresql
      - SPRING_DATASOURCE_PLATFORM=postgresql
      - DB_NUM=1
      - DB_URL_0=jdbc:postgresql://ao-postgres:5432/nacos
      - DB_USER=postgres
      - DB_PASSWORD=123456
      - DB_DRIVER_CLASS_NAME=org.postgresql.Driver
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_TOKEN=ao-platform-token
      - NACOS_AUTH_IDENTITY_KEY=nacos
      - NACOS_AUTH_IDENTITY_VALUE=nacos
    ports:
      - "8080:8080"
      - "8848:8848"
      - "9848:9848"
    volumes:
      - ./data/nacos/logs:/home/nacos/logs
    networks:
      - ao-network


networks:
  ao-network:
    driver: bridge
