server:
  port: 9300

spring:
  profiles:
    active: dev
  application:
    name: ao-platform-custom
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    virtual-host: /

    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 3
        max-concurrency: 10
        prefetch: 10
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=LSystemDB;encrypt=false
    username: sa
    password:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml
    type-aliases-package: com.ao.platform.custom.entity
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP
  config:
    import:
      - nacos:ao-platform-custom
      - nacos:ao-platform-custom-${spring.profiles.active}
      - nacos:ao-platform-security-${spring.profiles.active}
