server:
  port: 9300

spring:
  profiles:
    active: dev
  application:
    name: zhurong-platform-custom
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
    virtual-host: /

    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 3
        max-concurrency: 10
        prefetch: 10
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    table: flyway_schema_custom_history
    schemas: flyway_schema_custom
    default-schema: flyway_schema_custom
  datasource:
    dynamic:
      primary: lantek
      strict: false
      datasource:
        lantek: # SQL Server（主库）
          url: jdbc:sqlserver://localhost:1433;databaseName=LSystemDB;encrypt=false
          username: sa
          password:
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: localhost:8848
#        ip: 192.168.1.76
#        port: ${server.port}
      config:
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP
  config:
    import:
      - nacos:zhurong-platform-custom
      - nacos:zhurong-platform-custom-template-${spring.profiles.active}
      - nacos:zhurong-platform-security-${spring.profiles.active}


mybatis-plus:
  mapper-locations:
    - classpath:/mapper/**/*.xml
    - classpath*:/mapper-common/**/*.xml
  type-aliases-package: com.zhurong.platform.custom.entity
  configuration:
    map-underscore-to-camel-case: false

but-config:
  sync-nesting-reporting-maximum-days: 30
