server:
  port: 9200

spring:
  profiles:
    active: dev
  application:
    name: ao-platform-core
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: lantekha:8848
      config:
        server-addr: lantekha:8848
        file-extension: yaml
        group: DEFAULT_GROUP
  config:
    import:
      - nacos:ao-platform-core
      - nacos:ao-platform-core-${spring.profiles.active}
      - nacos:ao-platform-security-${spring.profiles.active}
