server:
  port: 9200

spring:
  profiles:
    active: dev
  application:
    name: ao-platform-core
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=LSystemDB
    username: sa
    password:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  cloud:
    nacos:
      username: nacos
      password: nacos
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml
        group: DEFAULT_GROUP
  config:
    import:
      - nacos:ao-platform-core
      - nacos:ao-platform-core-${spring.profiles.active}
      - nacos:ao-platform-security-${spring.profiles.active}
