CREATE TABLE AO_PLATFORM_NEST100_STATE_SNAPSHOT
(
    RecID     int,
    MState      smallint,
    LastDate   DATETIME,

    SyncTime DATETIME DEFAULT GETDATE(),
    CreateTime DATETIME DEFAULT GETDATE(),
    UpdateTime DATETIME DEFAULT GETDATE()
);
CREATE INDEX IDX_NEST100_SNAPSHOT_LASTDATE
    ON AO_PLATFORM_NEST100_STATE_SNAPSHOT(LastDate);